#! /bin/bash
#
# Muljed minu saavutustest
#
echo "Sulo Hipponen" # väljastab ees- ja perekonnanime
echo "ISP16" # väljastab õppegrupi
echo "Mulle meeldivad antud tunnid." #Aine tunnetus 
echo "Olen õppinud uusi asju ja arenenud." #Mulje ja edasijõudmine
#
#skripti lõpp
