#!/bin/bash pingimine
#pingimine IP_range 172.23.13.20-172.23.13.40

echo "Sisestage esimense ip lõpp: "
read esimene;
echo "Sisestage teise ip lõpp: "
read viimane;


for (( nr = $esimene; nr <= $viimane; nr++ ))
do
	ip = "172.23.13.$nr"
	ping -c 1 $ip
	if [ $? eq 0 ]; then
		echo "$ip - OK"
	else
		echo "$ip - Not OK"
	fi
done


